#----------------------------------------------------------------------------------------------------------------------#
# PROJECT NAME
#----------------------------------------------------------------------------------------------------------------------#
ProjectName = "NACA0012"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# PREPROCESSING METHOD
#----------------------------------------------------------------------------------------------------------------------#
MeshDimension = 3
#----------------------------------------------------------------------------------------------------------------------#
WhichMeshConstructionMethod = "mesh-builtin"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH REFINEMENT AROUND GEOMETRY
#----------------------------------------------------------------------------------------------------------------------#
InputGeometryFile       = "./ini/naca0012.stl"
InputGeometryFileFormat = "stl"
DebugGeometryImport     = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH BUILTIN
#----------------------------------------------------------------------------------------------------------------------#
DebugMeshBuiltIn = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
# MESH TYPE
#----------------------------------------------------------------------------------------------------------------------#
WhichMeshType = "cartesian-domain"
#----------------------------------------------------------------------------------------------------------------------#
# MESH OUTPUT BASIS
#----------------------------------------------------------------------------------------------------------------------#
WhichOutputBasis = "uniform"
#----------------------------------------------------------------------------------------------------------------------#
# MAPPINGS 3D
#----------------------------------------------------------------------------------------------------------------------#
WhichMapping3D  = "straight-hexa"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# COMPUTATIONAL DOMAIN
#----------------------------------------------------------------------------------------------------------------------#
nBoxElems3D = (/40,1,40/)
#----------------------------------------------------------------------------------------------------------------------#
BoxCorner = (/-20.0,+0.0,-20.0/)
BoxCorner = (/+20.0,+0.0,-20.0/)
BoxCorner = (/+20.0,+1.0,-20.0/)
BoxCorner = (/-20.0,+1.0,-20.0/)
BoxCorner = (/-20.0,+0.0,+20.0/)
BoxCorner = (/+20.0,+0.0,+20.0/)
BoxCorner = (/+20.0,+1.0,+20.0/)
BoxCorner = (/-20.0,+1.0,+20.0/)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH REFINEMENT INSIDE BOX
#----------------------------------------------------------------------------------------------------------------------#
nRefinedBox = 1
#----------------------------------------------------------------------------------------------------------------------#
RefinedBoxName = "airfoil"
#----------------------------------------------------------------------------------------------------------------------#
RefinedBoxCorner = (/-1.0,+0.0,-0.5/)
RefinedBoxCorner = (/+2.0,+0.0,-0.5/)
RefinedBoxCorner = (/+2.0,+1.0,-0.5/)
RefinedBoxCorner = (/-1.0,+1.0,-0.5/)
RefinedBoxCorner = (/-1.0,+0.0,+0.5/)
RefinedBoxCorner = (/+2.0,+0.0,+0.5/)
RefinedBoxCorner = (/+2.0,+1.0,+0.5/)
RefinedBoxCorner = (/-1.0,+1.0,+0.5/)
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# BOUNDARY CONDITIONS
#----------------------------------------------------------------------------------------------------------------------#
BoundaryMark = 1
BoundaryName = "bottom"
BoundaryMark = 2
BoundaryName = "front"
BoundaryMark = 3
BoundaryName = "right"
BoundaryMark = 4
BoundaryName = "back"
BoundaryMark = 5
BoundaryName = "left"
BoundaryMark = 6
BoundaryName = "top"
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# MESH REFINEMENT
#----------------------------------------------------------------------------------------------------------------------#
WhichMeshRefinement = "refine-elements-around-geometry-and-inside-box"
#----------------------------------------------------------------------------------------------------------------------#
WhichBoxedRegion = "adaptive-box"
#----------------------------------------------------------------------------------------------------------------------#
WhichBodyGeometry = "imported-geometry"
#----------------------------------------------------------------------------------------------------------------------#
DebugMeshRefinement = .FALSE.
DebugMeshElementsList = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
WhichGeometryDistribution = "stl-facets-distribution"
#----------------------------------------------------------------------------------------------------------------------#
TessellationMaxEdgeLength = 1.0E-02
ElementEnlargementFactor  = 10.0
RegionEnlargementFactor   = 0.1
#----------------------------------------------------------------------------------------------------------------------#
MaxRefinementLevel    = 10
MaxBoxRefinementLevel = (/6/)
#----------------------------------------------------------------------------------------------------------------------#
IsotropicRefinement  = .FALSE.
#----------------------------------------------------------------------------------------------------------------------#
#
#----------------------------------------------------------------------------------------------------------------------#
# EXPORT MESH PARAMETERS
#----------------------------------------------------------------------------------------------------------------------#
ExportMesh  = .TRUE.
#----------------------------------------------------------------------------------------------------------------------#
MeshExportFormat = "hdf5-coda"
MeshExportFormat = "tecplot-ascii"
MeshExportFormat = "gmsh"
#----------------------------------------------------------------------------------------------------------------------#
